### ISSUE TITLE
Meshview hbp app doesnt read colour from r g b params

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/MeshView-for-Brain-Atlases#49]
For some reason all the points load black
See this link for replication:
https://meshview.apps.hbp.eu/?atlas=AMBA_CCFv3_2017_full&cloud=https://data-proxy.ebrains.eu/api/v1/buckets/space-for-testing-the-nutil-web-applicat/71924239_s166_centroids.json

It occurs when uploading the cloud too. 

Let me know if you need anything else

**Comment by PolarBean** [comment]
This does not occur in older versions of MeshView: 
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_R&cloud=https://data-proxy.ebrains.eu/api/v1/buckets/space-for-testing-the-nutil-web-applicat/71924239_s166_centroids.json

**Comment by Tevemadar** [comment]
Color components are strings for some reason. Please supply them as numbers.
While it's not immediately obvious in the file (https://object.cscs.ch/v1/AUTH_7e4157014a3d4c1f8ffe270b57008fd4/space-for-testing-the-nutil-web-applicat/71924239_s166_centroids.json), because for some reason the RGB components are at the end of each cloud, jumping to the very end of the file shows
> `...], "r": "255", "g": "144", "b": "255"}]`

It should be `...], "r": 255, "g": 144, "b": 255}]`
